apiVersion: v1
kind: Pod
metadata:
  name: app-volumeMounts
spec:
  containers:
  - name: app
    image: gcr.io/tetris-effect-419120/k8s-k3s:v2.0.0
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "500Mi"
    volumeMounts:
    - name: data
      mountPath: /app/data
  volumes:
  - name: data
    configMap:
      name: app-data-configmap