apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
  labels:
    app: myapp
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mycontainer
            image: gcr.io/tetris-effect-419120/k8s-k3s:v2.0.0
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "400m"
                memory: "512Mi"
          restartPolicy: OnFailure