apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprobe
spec:
  containers:
  - name: app
    image: gcr.io/tetris-effect-419120/k8s-k3s:v2.0.0
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3