apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: app-secret-env-container
    image: gcr.io/tetris-effect-419120/k8s-k3s:v2.0.0
    resources:
      limits:
        cpu: 1
        memory: 512Mi
    volumeMounts:
    - name: app-secret-volume
      mountPath: /app/secret
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret