apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-livenessprobe
  labels:
    app: app-livenessprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-livenessprobe
  template:
    metadata:
      labels:
        app: app-livenessprobe
    spec:
      containers:
      - name: app-livenessprobe
        image: gcr.io/tetris-effect-419120/k8s-k3s:v2.0.0
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        env:
        - name: ENV_VAR
          value: "value"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred